#!/bin/bash

blue='\033[1;34m'
nc='\033[0m'

it='\033[3m'
ni='\033[23m'

curr_branch=$(git rev-parse --abbrev-ref HEAD)

echo -e "${blue}STATUS${nc}"
git status

if [[ $curr_branch != "main" ]]; then
    echo
    echo -e "${blue}COMMITS${nc}"
    git log --no-merges --pretty='%C(yellow)%h%d %Creset%an %Cgreen%ah%Creset %s' --graph main..
else
    echo -e "\n${blue}HISTORY${nc}"
    git log -n 10 --no-merges --format="%cd %h %<(16,trunc)%aN %<(48,trunc)%s" --date=format:"[%m-%d %H:%M]"
fi

echo -e "\n${blue}STASH${nc}"
stash=$(git stash list)
if [ -z "$stash" ]; then
    echo -e "${it}Stash is empty${ni}"
else
    echo -e $stash
fi
